name: s2-data-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.24.0
  - requests>=2.28.0
  - tqdm>=4.64.0
  - pip
  - pip:
    - boto3>=1.26.0
    - geopy>=2.3.0
