name: s2-data-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - requests>=2.28.0
  - tqdm>=4.64.0
  - matplotlib>=3.6.0
  - folium>=0.14.0
  - python-dateutil>=2.8.0
  - pip
  - pip:
    - boto3>=1.26.0
    - geopy>=2.3.0
    - polyline>=2.0.0
    - python-dotenv>=1.0.0
    - jsonschema>=4.17.0
